// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZyI0VVcdENZoRTwW5Ze3bQYRLQgp_Xl0',
    appId: '1:776719847961:web:2f69301d843863172a5088',
    messagingSenderId: '776719847961',
    projectId: 'transport-f7c79',
    authDomain: 'transport-f7c79.firebaseapp.com',
    storageBucket: 'transport-f7c79.appspot.com',
    measurementId: 'G-0P5JXEVERY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASx4Osx-gpV0qPm2mmDOtnkdHULXNmWYU',
    appId: '1:776719847961:android:775717916c8ad20c2a5088',
    messagingSenderId: '776719847961',
    projectId: 'transport-f7c79',
    storageBucket: 'transport-f7c79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQeJ7rFkX-UfHFzDOT_5zM1EfTf5es6W4',
    appId: '1:776719847961:ios:fb8ac8630baf34032a5088',
    messagingSenderId: '776719847961',
    projectId: 'transport-f7c79',
    storageBucket: 'transport-f7c79.appspot.com',
    iosBundleId: 'com.tayronausuario.tayronaUsuario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQeJ7rFkX-UfHFzDOT_5zM1EfTf5es6W4',
    appId: '1:776719847961:ios:fb8ac8630baf34032a5088',
    messagingSenderId: '776719847961',
    projectId: 'transport-f7c79',
    storageBucket: 'transport-f7c79.appspot.com',
    iosBundleId: 'com.tayronausuario.tayronaUsuario',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZyI0VVcdENZoRTwW5Ze3bQYRLQgp_Xl0',
    appId: '1:776719847961:web:a4aa7264934bd81a2a5088',
    messagingSenderId: '776719847961',
    projectId: 'transport-f7c79',
    authDomain: 'transport-f7c79.firebaseapp.com',
    storageBucket: 'transport-f7c79.appspot.com',
    measurementId: 'G-4VJ3D7Y0VH',
  );
}
