// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgVNuJAV4Ocn2qq6FoZFVLOCOOm2kIPRE',
    appId: '1:427872411983:web:8d3d12a267f0fb46f3a53a',
    messagingSenderId: '427872411983',
    projectId: 'tay-rona-flutter',
    authDomain: 'tay-rona-flutter.firebaseapp.com',
    databaseURL: 'https://tay-rona-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'tay-rona-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3GsIJaOaJOaWeWdS4ElcRWxor3Gx-IoA',
    appId: '1:427872411983:android:eb64849a94ebe827f3a53a',
    messagingSenderId: '427872411983',
    projectId: 'tay-rona-flutter',
    databaseURL: 'https://tay-rona-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'tay-rona-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9XehgtpAceKRJzqx8RTgGNwA70o76-XA',
    appId: '1:427872411983:ios:fabc34d013cfd496f3a53a',
    messagingSenderId: '427872411983',
    projectId: 'tay-rona-flutter',
    databaseURL: 'https://tay-rona-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'tay-rona-flutter.appspot.com',
    iosBundleId: 'com.tayronausuario.tayronaUsuario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9XehgtpAceKRJzqx8RTgGNwA70o76-XA',
    appId: '1:427872411983:ios:b2ea3b969b92ee15f3a53a',
    messagingSenderId: '427872411983',
    projectId: 'tay-rona-flutter',
    databaseURL: 'https://tay-rona-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'tay-rona-flutter.appspot.com',
    iosBundleId: 'com.tayronausuario.tayronaUsuario.RunnerTests',
  );
}
